import type { NextPage } from "next";
import Head from "next/head";
import {
  About,
  Achievements,
  Advantages,
  Products,
  Footer,
  Navbar,
  Trusted,
  MainSlider,
  Contacts,
  ShoesCategories,
} from "../components/mainPage";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Charm TJ - Производство обуви и других кожаных продукций</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/brands.min.css"
        />
      </Head>

      <>
        <Navbar />
        <MainSlider />
        <Advantages />
        <About />
        <Products />
        <Trusted />
        <Achievements />
        <ShoesCategories />
        <Contacts />
        <Footer />
      </>
    </>
  );
};

export default Home;
