import Head from "next/head";
import type { GetStaticProps, NextPage } from "next";
import { Apis } from "@consts";
import { IBannerDTO } from "@interfaces";
import { Send } from "@utils";
import {
  About,
  Achievements,
  Advantages,
  Products,
  Footer,
  Navbar,
  Trusted,
  MainSlider,
  Contacts,
  ShoesCategories,
  Video,
} from "@components/mainPage";

interface IProps {
  bannerImages: IBannerDTO[];
}

const Home: NextPage<IProps> = ({ bannerImages }) => {
  return (
    <>
      <Head>
        <title>Charm TJ - Производство обуви и других кожаных продукций</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/brands.min.css"
        />
      </Head>

      <>
        <Navbar />
        <MainSlider bannerImages={bannerImages} />
        <Advantages />
        <About />
        <Products />
        <Video />
        <Trusted />
        <Achievements />
        <ShoesCategories />
        <Contacts />
        <Footer />
      </>
    </>
  );
};

export const getStaticProps: GetStaticProps = async ({ params }: any) => {
  const bannerImages: IBannerDTO[] = await Send.Request("GET", Apis.getBanners);
  return {
    props: {
      bannerImages,
    },
    revalidate: 60,
  };
};

export default Home;
